version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing Docker and Gradle"
      - chmod +x gradlew

  pre_build:
    commands:
      - echo Logging in Amazon ECR..
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/z7i8c3d3
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean bootJar
      - echo Building Docker image..
      - docker build -t retoaws
      - docker tag retoaws:latest public.ecr.aws/z7i8c3d3/retoaws:latest
  post_build:
    commands:
      - echo Pushing Docker image..
      - docker push public.ecr.aws/z7i8c3d3/retoaws:latest
      - echo Writing image definitions..
      - printf '[{"name":"person-microservice","imageUri":"%s"}]'$AWS_ACCOUNT_ID.dkr.us-east-1.amazonaws.com/retoaws:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json