spring:
  application:
    name: awsProyect
  datasource:
    url: jdbc:mysql://retoaws.ckdeiesu8n6g.us-east-1.rds.amazonaws.com/person
    username: admin
    password: .Password123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "awsProyect System"
appVersion: "1.0"
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"