spring:

  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        profile-name: default
      parameterstore:
        enabled: true
      secretsmanager:
        enabled: true

  datasource:
    url:   ${jdbc_prefix}${rds_secret:host}:${rds_secret:port}/${rds_secret:dbname}
    username: ${rds_secret:username}
    password: ${rds_secret:password}

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true

appDescription: "awsProyect System"
appVersion: "1.0"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"