spring:
  application:
    name: awsProyect
  datasource:
    url: jdbc-secretsmanager${dbhost}
    username: rds_secret
    password: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "awsProyect System"
appVersion: "1.0"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"